version: "3.8" 
services:
  db: 
    image: postgres:12 
    volumes: 
      - type: volume
        source: web-app
        target: /var/lib/postgresql/data
    ports:
      - "2727:5432"
    environment: 
      POSTGRES_USER: drakenchef
      POSTGRES_DB: drakenchef
      POSTGRES_PASSWORD: drakenchef

volumes:
  web-app:
    driver: local
